// 业务异常码给前后端共用，避免接口报错时双方各写一套字符串。
export const BizCode = {
  COMMON_INVALID_REQUEST: 'COMMON.INVALID_REQUEST',
  COMMON_NOT_FOUND: 'COMMON.NOT_FOUND',
  AUTH_UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH.FORBIDDEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  AUTH_ADMIN_ROLE_REQUIRED: 'AUTH.ADMIN_ROLE_REQUIRED',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH.REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_REPLAYED: 'AUTH.REFRESH_TOKEN_REPLAYED',
  AUTH_SESSION_REVOKED: 'AUTH.SESSION_REVOKED',
  BIZ_CONFLICT: 'BIZ.CONFLICT',
  BIZ_RULE_VIOLATION: 'BIZ.RULE_VIOLATION',
  SYSTEM_INTERNAL_ERROR: 'SYSTEM.INTERNAL_ERROR',
  SYSTEM_UPSTREAM_TIMEOUT: 'SYSTEM.UPSTREAM_TIMEOUT'
} as const;

export type BizCode = (typeof BizCode)[keyof typeof BizCode];
